// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtVUliSb9CR_GUDWVCAP7YwcbSaOiWOzk',
    appId: '1:887624732505:web:15556fbd03d55082ab8648',
    messagingSenderId: '887624732505',
    projectId: 'learning-flutter-478bd',
    authDomain: 'learning-flutter-478bd.firebaseapp.com',
    storageBucket: 'learning-flutter-478bd.firebasestorage.app',
    measurementId: 'G-RBHNEWTRCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBADeV2Ln4fsihsBa3CZImQ9TCJ5TB26c',
    appId: '1:887624732505:android:9df96ef7c5523111ab8648',
    messagingSenderId: '887624732505',
    projectId: 'learning-flutter-478bd',
    storageBucket: 'learning-flutter-478bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzJb444mG9-GFwcGWzxf2kdxqpU-wsOWk',
    appId: '1:887624732505:ios:588c177a90a7d95aab8648',
    messagingSenderId: '887624732505',
    projectId: 'learning-flutter-478bd',
    storageBucket: 'learning-flutter-478bd.firebasestorage.app',
    iosBundleId: 'com.example.jdm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzJb444mG9-GFwcGWzxf2kdxqpU-wsOWk',
    appId: '1:887624732505:ios:588c177a90a7d95aab8648',
    messagingSenderId: '887624732505',
    projectId: 'learning-flutter-478bd',
    storageBucket: 'learning-flutter-478bd.firebasestorage.app',
    iosBundleId: 'com.example.jdm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtVUliSb9CR_GUDWVCAP7YwcbSaOiWOzk',
    appId: '1:887624732505:web:904b55f7603fe18aab8648',
    messagingSenderId: '887624732505',
    projectId: 'learning-flutter-478bd',
    authDomain: 'learning-flutter-478bd.firebaseapp.com',
    storageBucket: 'learning-flutter-478bd.firebasestorage.app',
    measurementId: 'G-82HZ1KR2B2',
  );
}
