import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:jdm/startscreen.dart';
import 'startscreen.dart'; // You will create this
import 'firebase_options.dart'; // Generated by Firebase CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '2D Racing Game',
      debugShowCheckedModeBanner: false,
      home: const StartScreen(),
    );
  }
}
